### PR TITLE
Fix verifier errors in ebpf/http-parse-sample.c

### PR DESCRIPTION
**Pull request by 0x59616e**

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Improve the git commit messages. See https://chris.beams.io/posts/git-commit/

**Comment by 0x59616e** [comment]
OK. I will improve that. Thanks

**Comment by jserv** [comment]
You should explain which "verifier errors" took place. Something like the instructions to reproduce and the initial analysis.

**Comment by jserv** [comment]
Once you confirmed that your pull request can resolve #3, you can append "Close #3" in the git commit message.
See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by 0x59616e** [comment]
OK, I will do that. Thanks

**Comment by jserv** [comment]
> OK, I will do that. Thanks

Any further action?

**Comment by 0x59616e** [comment]
Just copy and paste the commit message from iovisor/bcc@60b0166

Don't know whether it is OK ?

**Comment by jserv** [comment]
> Just copy and paste the commit message from [iovisor/bcc@60b0166](https://github.com/iovisor/bcc/commit/60b0166)
> Don't know whether it is OK ?

You should not blindly copy the git commit message. Instead, you can address the upstream fix and mention the reference materials.

**Comment by 0x59616e** [comment]
OK, I'll. Thanks ;)

**Comment by jserv** [comment]
Thank @0x59616e for contributing!

**Comment by 0x59616e** [comment]
Thanks @jserv ! Really appreciate ;)

**Pull request merged**
